name: biosync
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- FIREBASE (VERSÕES COMPATÍVEIS COM WINDOWS) ---
  firebase_core: 2.27.0
  firebase_auth: 4.17.4
  cloud_firestore: 4.15.8
  # --------------------------------------------------

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  
  # go_router mais recente NÃO é compatível com algumas libs antigas.
  # Baixar para versão ESTÁVEL recomendada:
  go_router: 14.8.0

  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-VariableFont_wdth,wght.ttf
